### ISSUE TITLE
Can't move a file between drives while getting content from AEM

### ISSUE THREAD

**Issue by toniedzwiedz** [devzbysiu/je#3]
I'm using `je` with IntelliJ on Windows 10 and I'm having a hard time `get`ting a file from CRX when working with a project checked out on a drive different from the one where IntelliJ and je are installed.

```
 DEBUG je::fsops  > writing cleaned lines back to file
 INFO  je::fsops  > moving files from C:\Users\TOMASZ~1.NIE\AppData\Local\Temp\.tmp0DKhrP\jcr_root\apps\bazbaz\components\xyz\.content.xml to Z:\home\tomasz_niedzwiedz\repos\foo\foo-aaa-aem\bar-bar-bar\ui.apps\src\main\content\jcr_root\apps\bazbaz\components\xyz\.content.xml
 DEBUG je::fsops  > files under C:\Users\TOMASZ~1.NIE\AppData\Local\Temp\.tmp0DKhrP\jcr_root\apps\bazbaz\components\xyz\.content.xml:
 DEBUG je::fsops  > 	- C:\Users\TOMASZ~1.NIE\AppData\Local\Temp\.tmp0DKhrP\jcr_root\apps\bazbaz\components\xyz\.content.xml
Error: The system cannot move the file to a different disk drive. (os error 17)
```
It appears to be caused by the `fs:rename` method being used in [`fsops.rs`](https://github.com/devzbysiu/je/blob/68395934877f6631fd97fd217dcf56b95f016e4d/src/fsops.rs#L163)

On Windows, https://doc.rust-lang.org/std/fs/fn.rename.html uses `MoveFileEx` internally. `MoveFileEx` does allow a flag to be set, which permits moving between drives, but this isn't something I can control through flags or variables when calling `je`.

Consider changing the way files are moved so that it's easier to work with multiple drives.

**Comment by devzbysiu** [comment]
Fixed in https://github.com/devzbysiu/je/commit/a405d0240562a1766c3aa60c7e541decfbb66af7 :slightly_smiling_face: . Instead of std implementation I used [fs_extra](https://crates.io/crates/fs_extra) which was in a dependency tree anyway. Closing
